# Generated by Django 6.0.3 on 2026-04-24 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0002_faculty_subject_code_faculty_subject_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='mobile_num',
            field=models.CharField(max_length=50),
        ),
    ]
