# Generated by Django 6.0.3 on 2026-04-24 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0003_alter_faculty_mobile_num'),
        ('HOD', '0002_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='hod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HOD.hod'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='mobile_num',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
