# Generated by Django 6.0.3 on 2026-04-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advicer', '0002_advicer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advicer',
            name='mobile_num',
            field=models.CharField(max_length=10),
        ),
    ]
