# Generated by Django 6.0.3 on 2026-04-19 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Advicer', '0004_classroom_username_alter_classroom_advisor'),
        ('Faculty', '0002_faculty_subject_code_faculty_subject_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Advicer.classroom')),
                ('subject_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Faculty.faculty')),
            ],
        ),
    ]
