# Generated by Django 6.0 on 2026-05-01 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Advicer', '0004_classroom_username_alter_classroom_advisor'),
        ('Faculty', '0004_faculty_hod_alter_faculty_mobile_num'),
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal1', models.FloatField(default=0)),
                ('internal2', models.FloatField(default=0)),
                ('assignment', models.FloatField(default=0)),
                ('total_marks', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Advicer.classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Faculty.faculty')),
            ],
        ),
    ]
