# Generated by Django 6.0.3 on 2026-05-02 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks',
            name='assignment',
        ),
    ]
