# Generated by Django 6.0.3 on 2026-04-11 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Faculty', '0002_faculty_subject_code_faculty_subject_name_and_more'),
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('subject_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Faculty.faculty')),
                ('usn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Student.student')),
            ],
            options={
                'unique_together': {('usn', 'subject_code', 'date')},
            },
        ),
    ]
