# Generated by Django 6.0.3 on 2026-04-19 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Advicer', '0004_classroom_username_alter_classroom_advisor'),
        ('Attendence', '0002_attendence_class_code'),
        ('Faculty', '0002_faculty_subject_code_faculty_subject_name_and_more'),
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendence',
            unique_together={('usn', 'subject_code', 'date', 'class_code')},
        ),
    ]
