# Generated by Django 6.0.3 on 2026-04-20 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attendence', '0003_alter_attendence_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendence',
            unique_together=set(),
        ),
    ]
