# Generated by Django 6.0.3 on 2026-04-20 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advicer', '0004_classroom_username_alter_classroom_advisor'),
        ('Attendence', '0004_alter_attendence_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='class_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Advicer.classroom'),
        ),
    ]
